version: 0.2
phases:
 install:
   commands:
     - curl -s https://getcomposer.org/installer | php 
     - mv  composer.phar /usr/local/bin/composer
     - npm install
     - npm run prod
     - php --version


 build:
   commands:
     - echo Build started on `date`
     - echo Installing composer deps
     - composer install
     - composer
     - cp .env.example .env
     - php artisan key:generate
     - php artisan config:cache
     - php artisan route:cache
     - php artisan cache:clear
     - cd $CODEBUILD_SRC_DIR
     - touch laravel
     

 post_build:
   commands:
     - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - '**/*'
secondary-artifacts:
  artifact1:
    base-directory: $CODEBUILD_SRC_DIR
    files:
      - laravel
  name: clyde-$(date +%Y-%m-%d)
